#pragma config(Motor,	 port2,						rightMotor,		 tmotorVex393, openLoop,		 reversed)
#pragma config(Motor,	 port3,						leftMotor,		 tmotorVex393, openLoop)
#pragma config(Motor,	 port4,						rearRightMotor, tmotorVex393, openLoop,		 reversed)
#pragma config(Motor,	 port5,						rearLeftMotor, tmotorVex393, openLoop,		 reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

//**************************** See this stuff? Dun touch it pl0x *************************
#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"		//Main competition background code...do not modify!
//*****************************************************************************************
//Wanna know what a function does? Read the name of it!

void pre_auton() {
	bStopTasksBetweenModes = true; //Don't know what this does but I assume it is important
}

void forward(int durration) {
	motor[rightMotor] = 100;
	motor[leftMotor] = 100;
	motor[rearRightMotor] = 100;
	motor[rearLeftMotor] = 100;
	wait1Msec(durration);
	return;
}

void backwards(int durration) {
	motor[rightMotor] = -100;
	motor[leftMotor] = -100;
	motor[rearRightMotor] = -100;
	motor[rearLeftMotor] = -100;
	wait1Msec(durration);
	return;
}

void left(int durration) {
	motor[rightMotor] = 100;
	motor[leftMotor] = -100;
	motor[rearRightMotor] = 100;
	motor[rearLeftMotor] = -100;
	wait1Msec(durration);
	return;
}

void right(int durration) {
	motor[rightMotor] = -100;
	motor[leftMotor] = 100;
	motor[rearRightMotor] = -100;
	motor[rearLeftMotor] = 100;
	wait1Msec(durration);
	return;
}

//Resets current commands (pause or full stop)
void kill() {
  motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	motor[rearRightMotor] = 0;
	motor[rearLeftMotor] = 0;
	wait1Msec(100);
	return;
}

//500 mSec == 90 degree turn
task autonomous() {
	forward(2000);
	kill();
  left(500);
  kill();
  forward(1000);
  kill();
}

task usercontrol() {
	//This does magic stuff for the driver
	while(1 == 1) {
		motor[rightMotor]	 = (vexRT[Ch2] + vexRT[Ch1])/2;
		motor[leftMotor] = (vexRT[Ch2] - vexRT[Ch1])/2;
		motor[rearRightMotor] = (vexRT[Ch2] + vexRT[Ch1])/2;
		motor[rearLeftMotor] = (vexRT[Ch2] - vexRT[Ch1])/2;
	}
}
