#pragma config(Motor,  port1,           fork,          tmotorVex393, openLoop)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393, openLoop)
#pragma config(Motor,  port4,           rearRightMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port5,           rearLeftMotor, tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port6,           lifterA,       tmotorVex393, openLoop)
#pragma config(Motor,  port7,           lifterB,       tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port8,           zFoldA,        tmotorVex393, openLoop)
#pragma config(Motor,  port9,           zFoldB,        tmotorVex393, openLoop, reversed)
#pragma config(Motor,  port10,          conveyor,      tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//**************************** See this stuff? Dun touch it pl0x *************************
#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"		//Main competition background code...do not modify!
//*****************************************************************************************
//Wanna know what a function does? Read the name of it!

void pre_auton() {
	bStopTasksBetweenModes = true; //Don't know what this does but I assume it is important
}

void forward(int durration) {
	motor[rightMotor] = 100;
	motor[leftMotor] = 100;
	motor[rearRightMotor] = 100;
	motor[rearLeftMotor] = 100;
	wait1Msec(durration);
	return;
}

void backwards(int durration) {
	motor[rightMotor] = -100;
	motor[leftMotor] = -100;
	motor[rearRightMotor] = -100;
	motor[rearLeftMotor] = -100;
	wait1Msec(durration);
	return;
}

void left(int durration) {
	motor[rightMotor] = 100;
	motor[leftMotor] = -100;
	motor[rearRightMotor] = 100;
	motor[rearLeftMotor] = -100;
	wait1Msec(durration);
	return;
}

void right(int durration) {
	motor[rightMotor] = -100;
	motor[leftMotor] = 100;
	motor[rearRightMotor] = -100;
	motor[rearLeftMotor] = 100;
	wait1Msec(durration);
	return;
}

//Resets current commands (pause or full stop)
void kill(int durration = 100) {
  motor[rightMotor] = 0;
	motor[leftMotor] = 0;
	motor[rearRightMotor] = 0;
	motor[rearLeftMotor] = 0;
	wait1Msec(durration);
	return;
}

//500 mSec == 90 degree turn
//Please kill after every movement
task autonomous() {
	forward(3000);
	kill(1000);
  left(500);
  kill(1000);
  forward(2000);
  kill(1000);
  right(500);
  kill(1000);
  forward(3000);
  kill();
}

task usercontrol() {
	//This does magic stuff for the driver
	while(1 == 1) {
		motor[rightMotor]	 = (vexRT[Ch2] + vexRT[Ch1])/2;
		motor[leftMotor] = (vexRT[Ch2] - vexRT[Ch1])/2;
		motor[rearRightMotor] = (vexRT[Ch2] + vexRT[Ch1])/2;
		motor[rearLeftMotor] = (vexRT[Ch2] - vexRT[Ch1])/2;
		//Control the conveyor here
		if (vexRT[Btn5U] == 1) {
			//Arm
	  } else if (vexRT[Btn5D] == 1) {
	    //Arm
	  } else if (vexRT[Btn6U] == 1) {
	    //Fold
	  } else if (vexRT[Btn6D] == 1) {
	    //Fold
	  } else if (vexRT[Btn7D] == 1) {
	    //Fork
	  } else if (vexRT[Btn7R] == 1) {
	    //Fold
	  }
	}
}
